<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="DNTPersianUtils.Core" Version="6.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductionSystem.Domain\ProductionSystem.Domain.csproj" />
  </ItemGroup>

</Project>
