<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductionSystem.Application\ProductionSystem.Application.csproj" />
    <ProjectReference Include="..\ProductionSystem.Infrastructure.Data\ProductionSystem.Infrastructure.Data.csproj" />
  </ItemGroup>

</Project>
